### ISSUE TITLE
State of the input-pad development

### ISSUE THREAD

**Issue by nikita-moor** [fujiwarat/ibus-input-pad#1]
After short test of the `ibus-input-pad` I found it partially functioning:

1. Switching to input-pad IM does not show the main windows (though it still can be activated through the menu "Lunch Input Pad > Show Input Pad").
2. Main windows does not stay "always on top".
3. ~Nothing be typed (active window focus problem?).~ (v1.4.2 is OK)
4. Main window resizing is useless.
5. Input-pad does not remember the last browsed category (isn't convenient).

Last activity in `input-pad` project was observed in 2016 year, is it still under development? Could you recommend an analog or replacement?

**Comment by nikita-moor** [comment]
Is `ibus-input-pad` intended to be used with a particular language and be called in case of need from menu? I work with several languages and would like to switch to `ibus-input-pad`, show main panel at once, select a symbol, and switch back to my language. For example: Chinese (libpinyin) > input-pad > Chinese. Is it possible?

**Comment by fujiwarat** [comment]
> 1. Switching to input-pad IM does not show the main windows (though it still can be activated through the menu "Lunch Input Pad > Show Input Pad").

Yes, it's an expected result.
I can add a new shortcut key to launch the input-pad window but I prefer not to show it by default.

> 2. Main windows does not stay "always on top".

Because the keyboard layout in input-pad can send the characters to an application which is focused on previously.
Also I mind if a bug happen in the focus problem by a desktop, users would not change the focus by click.

3. ~Nothing be typed (active window focus problem?).~ (v1.4.2 is OK)

?
The latest input-pad & ibus-input-pad works fine with me.
Note: recently gtk does not accept XSendEvent so you need to enable XTest feature in input-pad when you build input-pad.

> 4. Main window resizing is useless.

Yes, I know it. Probably I'd disable the resizing window.

> 5. Input-pad does not remember the last browsed category (isn't convenient).

Which category do you use frequently?
input-pad does not save any preferences but ibus-input-pad could have that setting.

**Comment by fujiwarat** [comment]
> For example: Chinese (libpinyin) > input-pad > Chinese. Is it possible?

I don't understand your issue.
You can switch ibus engines with Super-space key.

**Comment by nikita-moor** [comment]
I will try to be more clear.

For example, I use "us(intl)" layout and want to use input-pad. Then I should open `input-pad.xml` and set desired layout:

```xml
<engine>
  …
  <layout>us</layout>
  <layout_variant>intl</layout_variant>
  …
</engine>
```

If I use several layouts (8 in particular), probably several `<engine>`s could be added into `input-pad.xml` (didn't check it yet). However, it is applicable onyl to XKB layouts (ibus-xkb engine), but how could input-pad be used with ibus-m17n, ibus-anthy, libpinyin and many other engines?

I see input-pad as a layout I could switch to, choose a symbol of interest, and back to my layout. Therefore, input-pad is not a layout for constant use, but a secondary one. That is why I want the main window be activated and deactivated every time I switch to/from input-pad engine.

Another explanation. Currently, I run with a hotkey this script:

```sh
input-pad --with-table-type=1 | xsel --input --clipboard
```

then I choose several symbols, close the window and past the symbols into text. The "xsel" is needed because input-pad w/o ibus cannot type symbols directly (am I correct?). So, I would like to have ibus-flavour of input-pad to simplify this process, but do not want to affect my layouts.


> I can add a new shortcut key to launch the input-pad window but I prefer not to show it by default.

Could it be a flag like "showpanel"?

```sh
/usr/libexec/ibus-engine-input-pad --ibus --showpanel
```

Input-pad window called with a hotkey and staying on the screen to be used when necessary, like a virtual keyboard, is a possible variant too. More over, now I think it would be the best variant for me, kind of [ibus emojier](https://desktopi18n.wordpress.com/2018/03/06/ibus-1-5-18-is-released/) but allowing to pick up several symbols and remembering the category (search is a good idea too).


> The latest input-pad & ibus-input-pad works fine with me.

I will try to compile the last (prerelease) version.



> > Main window resizing is useless.

> Yes, I know it. Probably I'd disable the resizing window.

It is OK, though correct resizing of the window's elements (and preserving of these settings) would be wonderful because looking through big categories with hundreds of symbols in a small window is tiresome.



> > Input-pad does not remember the last browsed category (isn't convenient).

> Which category do you use frequently? input-pad does not save any preferences but ibus-input-pad could have that setting.

For example, I am typing a text with sporadic Egyptian hieroglyphs and need to open input-pad from time to time on the same category. Another day it can be Dingbats category, so it is not a favourite category but simply "the last used".

**Comment by fujiwarat** [comment]
ibus-input-pad's layout is `default` and it does not change any layout which was set by the previous ibus engine. So even if you have many layouts engines, ibus-input-pad just uses the previous layout and I don't think to prepare ibus-input-pad by layout.

>  That is why I want the main window be activated and deactivated every time I switch to/from input-pad engine.

But you need to activate an input context of an application before you launch input-pad.
If you activate desktop background before you launch input-pad, ibus-input-pad does not send characters.
So you sometimes might need to close input-pad window if you failed to get an input context.
That's why I like to hide input-pad by default but I understand your request.

> Could it be a flag like "showpanel"?

I meant to run "Show input pad" with Ctrl-Home and "Hide input pad" with Ctrl-End key and then you don't need to use mouse but type Super-Space and Ctrl-Home.
But it seems your flag means to always launch input-pad instead.
Then probably I think a configure option on `ibus-setup-input-pad` instead of the argument of `ibus-engine-input-pad`

> For example, I am typing a text with sporadic Egyptian hieroglyphs and need to open input-pad from time to time on the same category. Another day it can be Dingbats category, so it is not a favourite category but simply "the last used".

When you choose "Dingbats" category, the last one would become "Dingbats" so you choose "Egyptian" by manual?
